name: MCValorant
version: 0.2.3
api-version: 1.17
author: AV3_08
main: me.av306.mcvalorant.Main
description: behaviour

commands:
  match:
    description: control match
    usage: /match <start | end | panic>

  giveweapons:
    description: give weapons
    usage: /giveweapons
    permission: op